### ISSUE TITLE
TypeError: Object #<Object> has no method '$'

### ISSUE THREAD

**Issue by vinitkumar** [rubenstolk/backbone-ssr#1]
Getting this error after doing a fresh `npm install` and `npm start`

``` js
TypeError: Object #<Object> has no method '$'
    at Object.handle (/Users/vinit/projects/javascript/backbone-ssr/config/middlewares/ssr.js:80:12)
    at next (/Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle] (/Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:49:5)
    at next (/Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/middleware/multipart.js:64:37)
    at /Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at urlencoded (/Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:51:37)
    at /Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
    at json (/Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/middleware/json.js:53:37)
    at Object.bodyParser [as handle] (/Users/vinit/projects/javascript/backbone-ssr/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
```

**Comment by vinitkumar** [comment]
maybe cause there is no file in the /app/boilerplate but it is referenced in the template.
`<script data-main="/app/config" src="/app/boilerplate/libs/require.js"></script>`

**Comment by vinitkumar** [comment]
Oh, my bad. Didn't do a `git submodule update --init --recursive` 
Send a PR with installation details in the readme.
